### PR TITLE
fixed ashley becnhmarks

### PR DESCRIPTION
**Pull request by piotr-j**
Fixed pooled benchmark, fixed bug in ManglerSystem so it actually removes correct number of entities. 

Implemented best practices for getting components from entities and acquiring Family bits.

### CODE REVIEW

**Comment by junkdog** [comment]
Thanks!

Could you revert the Family changes though? The Family class was updated in 1.3.2.

**Comment by junkdog** [comment]
I ended up, inadvertently, manually applying most of your PR, in the process fixing an error I had in my local 1.3.3  benchmarks. Turned out that your ```Entity e = entities.get(i);``` was the solution to fixing an out-of-memory error.

I haven't touched the 1.3.1 benchmarks though, but I can apply them manually too, or just revert the family stuff in the PR.

Anyway, just wanted to say thanks for spotting the error in ```EntityManglerSystem```. Saved me a lot of head-scratching.

**Comment by piotr-j** [comment]
Messed up a bit, but i've reverted the family changes. The failing insert/remove bench was the main thing I wanted to fix, I am planning to switch to artemis and wanted to run the benches myself.

**Comment by junkdog** [comment]
Thanks :) Running all the benchmarks myself now - should release artemis-0.9.0 in the next couple of days.

**Pull request merged**
